import PySimpleGUI as sg
import matplotlib.pyplot as plt
import pandas as pd
import os
import sys

defaultImg = "iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6CAIAAAAHjs1qAAAACXBIWXMAAA7EAAAOxAGVKw4bAAA8jGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxMzggNzkuMTU5ODI0LCAyMDE2LzA5LzE0LTAxOjA5OjAxICAgICAgICAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgICAgICAgICB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIgogICAgICAgICAgICB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOmV4aWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vZXhpZi8xLjAvIj4KICAgICAgICAgPHhtcDpDcmVhdG9yVG9vbD5BZG9iZSBQaG90b3Nob3AgQ0MgMjAxNyAoV2luZG93cyk8L3htcDpDcmVhdG9yVG9vbD4KICAgICAgICAgPHhtcDpDcmVhdGVEYXRlPjIwMjMtMDQtMDJUMTc6NTY6MTMrMTI6MDA8L3htcDpDcmVhdGVEYXRlPgogICAgICAgICA8eG1wOk1ldGFkYXRhRGF0ZT4yMDIzLTA0LTAyVDE3OjU2OjEzKzEyOjAwPC94bXA6TWV0YWRhdGFEYXRlPgogICAgICAgICA8eG1wOk1vZGlmeURhdGU+MjAyMy0wNC0wMlQxNzo1NjoxMysxMjowMDwveG1wOk1vZGlmeURhdGU+CiAgICAgICAgIDx4bXBNTTpJbnN0YW5jZUlEPnhtcC5paWQ6NzZiZmZiMTAtOGRhNy1lMjRlLWE3YWEtMGI3Y2E1ZWE0ZTQwPC94bXBNTTpJbnN0YW5jZUlEPgogICAgICAgICA8eG1wTU06RG9jdW1lbnRJRD5hZG9iZTpkb2NpZDpwaG90b3Nob3A6MTM0ZWRhNjMtZDExYi0xMWVkLWJiZDItZDhkYzJjMWNhZjg5PC94bXBNTTpEb2N1bWVudElEPgogICAgICAgICA8eG1wTU06T3JpZ2luYWxEb2N1bWVudElEPnhtcC5kaWQ6ZjBhOWZkZDgtYzY5Yi04YTQ5LTljMTMtMDRhNTY1NThkNzE3PC94bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ+CiAgICAgICAgIDx4bXBNTTpIaXN0b3J5PgogICAgICAgICAgICA8cmRmOlNlcT4KICAgICAgICAgICAgICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDphY3Rpb24+Y3JlYXRlZDwvc3RFdnQ6YWN0aW9uPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6aW5zdGFuY2VJRD54bXAuaWlkOmYwYTlmZGQ4LWM2OWItOGE0OS05YzEzLTA0YTU2NTU4ZDcxNzwvc3RFdnQ6aW5zdGFuY2VJRD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OndoZW4+MjAyMy0wNC0wMlQxNzo1NjoxMysxMjowMDwvc3RFdnQ6d2hlbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnNvZnR3YXJlQWdlbnQ+QWRvYmUgUGhvdG9zaG9wIENDIDIwMTcgKFdpbmRvd3MpPC9zdEV2dDpzb2Z0d2FyZUFnZW50PgogICAgICAgICAgICAgICA8L3JkZjpsaT4KICAgICAgICAgICAgICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDphY3Rpb24+c2F2ZWQ8L3N0RXZ0OmFjdGlvbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0Omluc3RhbmNlSUQ+eG1wLmlpZDo3NmJmZmIxMC04ZGE3LWUyNGUtYTdhYS0wYjdjYTVlYTRlNDA8L3N0RXZ0Omluc3RhbmNlSUQ+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDp3aGVuPjIwMjMtMDQtMDJUMTc6NTY6MTMrMTI6MDA8L3N0RXZ0OndoZW4+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDpzb2Z0d2FyZUFnZW50PkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE3IChXaW5kb3dzKTwvc3RFdnQ6c29mdHdhcmVBZ2VudD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmNoYW5nZWQ+Lzwvc3RFdnQ6Y2hhbmdlZD4KICAgICAgICAgICAgICAgPC9yZGY6bGk+CiAgICAgICAgICAgIDwvcmRmOlNlcT4KICAgICAgICAgPC94bXBNTTpIaXN0b3J5PgogICAgICAgICA8cGhvdG9zaG9wOlRleHRMYXllcnM+CiAgICAgICAgICAgIDxyZGY6QmFnPgogICAgICAgICAgICAgICA8cmRmOmxpIHJkZjpwYXJzZVR5cGU9IlJlc291cmNlIj4KICAgICAgICAgICAgICAgICAgPHBob3Rvc2hvcDpMYXllck5hbWU+VGhlIHZpc3VhbGl6ZWQgcmVzdWx0cyBhcmUgZGlzcGxheWVkIGhlcmU8L3Bob3Rvc2hvcDpMYXllck5hbWU+CiAgICAgICAgICAgICAgICAgIDxwaG90b3Nob3A6TGF5ZXJUZXh0PlRoZSB2aXN1YWxpemVkIHJlc3VsdHMgYXJlIGRpc3BsYXllZCBoZXJlPC9waG90b3Nob3A6TGF5ZXJUZXh0PgogICAgICAgICAgICAgICA8L3JkZjpsaT4KICAgICAgICAgICAgICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgICAgICAgIDxwaG90b3Nob3A6TGF5ZXJOYW1lPlRoZSB2aXN1YWxpemVkIHJlc3VsdHMgIGRpc3BsYXkgaGVyZSBBU0FQPC9waG90b3Nob3A6TGF5ZXJOYW1lPgogICAgICAgICAgICAgICAgICA8cGhvdG9zaG9wOkxheWVyVGV4dD5UaGUgdmlzdWFsaXplZCByZXN1bHRzICBkaXNwbGF5IGhlcmUgQVNBUDwvcGhvdG9zaG9wOkxheWVyVGV4dD4KICAgICAgICAgICAgICAgPC9yZGY6bGk+CiAgICAgICAgICAgIDwvcmRmOkJhZz4KICAgICAgICAgPC9waG90b3Nob3A6VGV4dExheWVycz4KICAgICAgICAgPHBob3Rvc2hvcDpDb2xvck1vZGU+MzwvcGhvdG9zaG9wOkNvbG9yTW9kZT4KICAgICAgICAgPGRjOmZvcm1hdD5pbWFnZS9wbmc8L2RjOmZvcm1hdD4KICAgICAgICAgPHRpZmY6T3JpZW50YXRpb24+MTwvdGlmZjpPcmllbnRhdGlvbj4KICAgICAgICAgPHRpZmY6WFJlc29sdXRpb24+OTYwMTIwLzEwMDAwPC90aWZmOlhSZXNvbHV0aW9uPgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj45NjAxMjAvMTAwMDA8L3RpZmY6WVJlc29sdXRpb24+CiAgICAgICAgIDx0aWZmOlJlc29sdXRpb25Vbml0PjI8L3RpZmY6UmVzb2x1dGlvblVuaXQ+CiAgICAgICAgIDxleGlmOkNvbG9yU3BhY2U+NjU1MzU8L2V4aWY6Q29sb3JTcGFjZT4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjI1MDwvZXhpZjpQaXhlbFhEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWURpbWVuc2lvbj4yNTA8L2V4aWY6UGl4ZWxZRGltZW5zaW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAKPD94cGFja2V0IGVuZD0idyI/Pr4GSMsAAAAgY0hSTQAAeiUAAICDAAD5/wAAgOkAAHUwAADqYAAAOpgAABdvkl/FRgAAF25JREFUeNrsnUFoG0fbx6cfPSkxIRiHml6cdlPyIhLjNwQnwVQktsnbQ3AJG5qDgikOqDE0UNOAcghN6EGGFh9cUCyoaIJyMRZGJoe4RGpQMOqKlxejRKKh3lY6tCRYhFIS6arv8CiPx7Or9cqW0yj5/8hhs5qdnZn9z+wzz4z3eatWqwkA3gz+D00AIHcAIHcAIHcAIHcAIHcAIHcAIHcAIHcAIHcAIHcAIHcAuQMAuQMAuQMAuQMAuQMAuQMAuQMAuQMAuQMAuQMAuQPIHQDIHQDIHQDIHQDIHQDIHQDIHQDIHQDIHQDIHQDIHUDuAEDuAEDuAEDuAEDuAEDuAEDuAEDuAEDuAEDuAEDuAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDsAjrztPmmhUFheXhZC9PX1eb3eV6H01Wq1WCzu3bvX4/H8syUplUqTk5NCiN7e3gsXLsjnhRA9PT0vv0i3bt2iA7/f316ivH79ei6XE0IEg8F/oOny+XytVovFYvTfWCxWezXQdV0Ioev6P16SfD5PjRMIBPikYRh00jCMl18kfny1diMQCMjCayFtbMwUCoV4PC6EiMfjhULhFSzhDz/8oByAf9iY4TFbCHHu3Dkev+VEe/bseQWL7vV6dV2Px+O6rr8ixpXCp59+GolE6ABS2zrlcjmTybzzzjv9/f2blLts2LHc28Xam5ubKxQKr6bWhRD9/f2rq6tCiK6uLoh1iywsLHz88cc0Fm9e7u3eCq+s1gkIvVU8e/bspXpmrF6Rhw8frqys7Nu378CBAw6+EXbpbJiSEtOB1d9CfhghxI4dO2jCzomtos9msysrK9abWjOR35U0GO/Zs0eRaaFQME2TWty9Y8qaIZ+xxVokbuQN71sulx88ePD8+XNN09wPAdwa1NrVavXnn38WQgwODip+p1wu9+zZs+7u7oMHDzbqw6VSaWlpSQihJNtcmytp/vjjD/rvH3/8Qc9dyY0K//jxY6e2cj+Xlz0zyWRS0zROr2lasVi0XmIYhpyMUiaTSYe5czAYpJTWZOFwmH5KJBIOBS4Wiz6fT7np6uqqgwvFWkE+mUwmldyEED6fT6mvbbbWDJVJkYJSJGti631rtdrq6iq7MuRkbjwzXOx8Ps/PVC5GsVgk95dMOBxW8qlUKkoZZH9Us22ueGYaNZqcmyLIRv66zYzuCwsL8Xhc07RAIJBKpUzTNE1zeHg4k8nIHTSVSg0NDVHrnz9/Xgjx/fffp9PpoaGhZDKpjB/M0NAQObCtaWZnZ+ng2LFjDoPc8PCwaZrUHFSMd999d9NGxfPnz9PptKZpVJhHjx6l0+l0Oj08PJzL5Vrr79+9ezcfT05OXr58mWoxMDDw7Nmzqakpuu/du3d5VKtWq8eOHaP6UmIq4fDwcFO3fvLkCT0sZbSmxtQ0bWJioqOjY2lpKRKJjI+P//333zwwCSFGR0fJS6bremdnJ5Xhvffeezl2TjabpcLzY4pEIocOHWrN6C6ECIVClUqFujX3frnT8+gSCoXkMYASa5pGl1upVCp8FzkN2wByn7YWmN8AsstWOW5qpCkWi4rXnB+zXF+Xo7uV1dVVHpZ45E4kEtZXXLFYtI6+PBDqui6/weShzs3oTumDwaBhGFSMSqVCrzVd1+UHEQqFlBbm5QW5mltpc1u/u0NjWkVVqVRszY3NyN3n8ykWi/X1QY1ilTUndjBpWE+yzmwVYC0wt1RT60Hu1Sn3ZLm+m5Y7DxZsodVqNdKZtYTcmUnZPARY21kem9zIXRmYyDywXevh8YjT870arQptt9wbZd6aZSayTGR3Gx3Q64yIRqNCiLGxMeV1z4l//fXXRvmTv0kIce/ePT7JS+JHjx51KBu/5a9fv74d781CocDPW67v5rh+/TplEggERkZG2IRIp9NCiDNnzijpP/zwQzr4/fffhRCZTIb+a23n06dPN1uYixcvyv8luft8PmXO5/F4SI7/+9//6Ex3dzcdfPfdd9Vq9eU7bWh0iEQi2Wz2H3BElkolsiYXFxdp04gV2hTRyF2taZppmtFolEb6arVKsggGg87m8tmzZ8nkHR8fn52dvXLlSqNJQlM+qPn5eZqxtNbiHB8fp7F5amrK2jIzMzNzc3PyJU+fPqWDlZWV/v7+X375hf57/PhxJfNmJxWBQEC5hCr7559/fvbZZ0riVCol9/ajR4/6fL50Oh2JRFKp1FdffXX69OmXuYvpiy++oAHiyJEjgUDg888/b+Sb2ha58/hHs7pN5DA2Nnb58mXTNGkVibxj8sDvMLobhuH3+03TpLv7fL4bN25seqcRT9fYgOns7KS10i12IV7Lu3XrliwOdjBv2Lt4KNm5c2fLHyJVmfwQzik9Hs+NGzcuXboUj8dN0zx37ty1a9dmZma2PtC4ZGRkJBaL0SJpJBKJRCKBQGBqasra5bZ3mSkUCp06daqRj9nhQh6u7t+/7/V66cWqaZqb5bT+/v5cLjc/P3/t2jUSvdVr5BLZz5NIJIaHh6kFty73iYkJyjYUCjWqVCKRUJxrzEvb1qHr+tWrVzdM1tPTMzc3l0qlvv7663Q6bZrm0NCQYRibXv5sFr/ff/LkyWg0Su/2SCTy9OlT5d24XXLfu3cvH29u1ZPtmZ9++unChQs0zo2Njbm83OPx+P3+06dPT09P01siHo/L+3JdkslkSJSxWIxt662zsLBAHcbn8ykWM62L8Zjt3Hr8yjJNs+Wry7QfqVwuu895cHBwcHCQV/u//fZbq+C2j66urmAwODY2Nj4+Ho/H4/F4NptV+tu27Ij0eDw0e4hGo5ueu0xMTNALPZvNkubOnj3bbDFYTGwQ81uFDFAZXrdj7ty5Qwd9fX2yHbLFiQ2bZDdu3LC+cNldvaFWDh8+rJRTnhhs8SGS3zqdTje723RkZITcTWyMNdXmWxf9l19+yTMc5dft2gBM3hvTNKenpzenj48++ogOaPesz+dzY383uhev4MgjovwgS6USvQdtr3ry5AmfvHv37lZa5tKlS+z6sK1RV1cXuT4ikcjCwoJDVuyksjoltr7lmK3Qq1evlsvlTbQ5W2JNtXkjOjo6GvWQRgXgS4StU9al372R41O+UF5+8vl8sVgsn8/TSnU4HFZcvI2QV++tC9e29w2FQsFgMJlM5vN5wzC4DLK3nhdKNE1LJBL5fD4Wi8lWMleQfc+aphmGQSltW8+l350d55qmxexQVpQoQypkPp9PJBKhUEj20MvlCYfD1MK87OLe727rtJYbKhwOUwsYhhGLxeQ1B7ojF5KXTeSn7L7NG/nd5W0RJCdeSNJ1PRQKUfHk3QS87ralZSY3cqdFEOt2C+4AbuTO4rAtuu19bed2Su+qVCrWZJqm8bOXK2itgq7r1sUsl3LfcAyTM2w0T1Wqw0qSCYfD3HqblnulUrHNXHki8m4CuZXkla+m2rzRXzMpz4LaQe4GyrrBBntmrLt8ZLq7uykBLys4X9jV1UWz9WQySZNFStnT08NG54b2DOXc09Nj61ex3ndmZiaZTJJHjBKcOXNG8Yh5PJ5cLjc9Pb24uJhOp3VdP3HihK7rbEXIFbx58+ahQ4ei0ahpmrT5x+/3s41RLpepYDt27KBre3t7HVrMuYVlvF5vLpe7e/funTt3aAsKbQjp7e3lxSYiGAwePnyYak068/v9Xq83lUpteDvbYssNFQwGT506dfv27VKpRNNrXdc1TTty5Ahb5H6/f9euXdSYlGBkZERxvTfV5r29vXRScd/Rs6AcfD7frl27yEmVSCTu3LlDxdM0jVvAWqO33Aw5ALwe4MMbAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDt4I3n7NahDKpWi8IInT55Ughtao1W29r701VLrl5u2FQ5k0i7Rnl8hau2P7TfW6ANrttEGW4XLWE4t53V6di+Z19OYKRQK9AW5eDze7PeaAWz3NsPr9fLo/opHkQew3VvA3NwcxXXCMwZvhGcGWgdtP7pXq9WHDx+urKz09fU5OF7YZLeKPpvNUhiTffv2HThwgHMgZ44QgrMtFArLy8vd3d3vv/9+U7H7CoWCaZoUQ6+vr08pQ6lUouCEe/bsUT7kzWVw311LpRKF4unt7XUoZLlcfvDgwePHjzs6OmxTUql27NhBP5VKpaWlJdnZxVVbXl62th48My2mUqnIAQ6EEJqmJZNJW8+MbQWLxaIcEYRykGOrcz75fF5JGQgEGkWmlj0zyWRSuVAI4fP55JjlHAE8GAwqdeSo4tafrFWrVCrKF9xtw6JUKhVrxAFrdSgrOm/bpIZhKCEJqP3bSELtJHf50eq6zrEc+Bk4y311dVWOABMIBDRNk+OIsNw5ZIV8F2GJSGErd5Kypml0C5a+HMedg7uTZG1DcTjISC6PtZBKVB85alAoFIrFYnLt5Luz3OWIHdykHLeHQg/FYjGuWhspvm3kztqiCCe28XCc5c5vBjmZciyPW/yT/E6QxWQr92KxaBiGXHIeWeVr+aSiFb6R0g1s5S4XkuWoXEs30jRNfr1wYmuIGBoROIISZcX2lfz24I4k92TIvTWwDpR4PbJGneVuDajUKFCRw100TWt2mYm1ooTvshotnNLBkpGrpnQV7vnc3/g1Yi0hJZZfbtw+St/gd45V1mx6tcsA3x6emVKpRHF/fD6fMoFjF/uG8OTs+vXrzikd7qKESnQzZ6VZqVgf9H1wcJDG0cnJSY6TyMFfh4aG3GSu7FzgQMccTzSTydDByZMnlWspcTqdtkZpnJiYUCay0WhUCDE2NqZMTDlI76+//grPTMv47bff6OCTTz6x/trZ2ekmk7Nnz1IUz/Hx8dnZ2StXrjTa6LJ//37ryRMnTpBel5eXnX0m1Wp1fn5+YWFB1reVsbExKs/Dhw9JNxQNWNM0Dpi6RXj0vXLlivLTo0eP6KBYLCrVUUKdlUoliuu2uLhYKpVsb8QdFXJvAbQDTNgGhnVNT0+PYRh+v980zXQ6TdHbbty44dLD6PLWpVJpeHiY9EEGTGdnJwWFUzh16hTJ/d69e/39/dVqlZJZB9FN89dff9GBbQFcwm8najT43duG/v7+XC43Pz9/7do1Ev3w8HAmk7GNYrkJyuUyaz2RSAwPD5NwbdXm9Xp9Pl86nY5Go8Fg8OHDh3T++PHjLa+4PC1R2Lt3r8tMQqEQh9JWUCJCQu5bgoNubn2/l8fj8fv9p0+fnp6evnz5MgV8vXDhghsrnA76+voapclkMqT1WCzGlrQD58+fT6fTNB+4d+8eWTJsEG8djpZqXc9yj9wf2n2huj2mqgcPHuTZnjK1YhugWdFfvHixkd2ZSqWs5jgb4g7DIRnfSpewzgUZnkHev39/cXGRLJkWttsHH3xABz/++ONWBghyi0WjUYe6QO4to6urix0jN2/elH+an593mUmjR7V7927ljGmaHBebmJ6e5jDcDoY1Z/XkyRM+effu3Q3rNTs7S2ZxI2thcxw9epT8P9euXdvKi/H8+fPULNPT0+2t+Hbxu8vWZzAYNAzDMAxeQ2EL1cHvHgqFgsFgMpnM5/OGYbD7kn3GioEbCoXku7Afw8Hvzt50TdMMw8jn85ymUWvLy0OyF3wTf97RaFODXCOqPhUsEAjI1bHdOGBdmqVVVcokmUyGw2HbnQtYZtoq8pNjAoEAn3eWu7LfgxVg7VHKsjwrWFlMsZWX9UJd1x1WuNjvIVz/VVRTcpe36FiRa+Qgd+sCtozLXvoq0E6emcHBwXw+f/v27cXFxXQ6HQgE6I9ES6USPSrZP6DsnRJCzMzMJJPJeDzOZkmjvzHt7OycmpoaGRlZWlqKRCK6rh86dGhsbEyZ7XV3d9NdeCYthLh58+ahQ4ei0ahpmj6f7/z5836/n02jcrmsZOLxeHRdp4mBdTHIFmvVHMojhBgZGVldXY3H47lcLpVKUcH2798/MDDAkyKa11qbUba75ubmUqlUMpmk+T2VpKen5/DhwzBm2g8e3QOBwMu/aRuZBPhbVbAZqtXq1atX6bi1PhnQxp6Z11Xro6OjZBWEw+FWLXUByP2VY2Fhobe3l7Su6/ro6CjaBHJ/bTEMg2bMuq5/8803bfYncG3LW7Jj6w2nXC7T6mN3d/d2fxUslUoNDQ2Fw+HR0VFoHXJ//Q13IQSEDrkDANsdAMgdAMgdAMgdQO4AQO4AQO4AQO4AQO4AQO4AQO4AQO4AQO4AQO4AQO4AQO7gTeJtNEETlEqCP/rl5lu4hYJ48kQ8fiw6OoSmbXAJf8Nxxw7R6JPz5bKg+DPLy/Uz+/aJnTsFIsi6BJ/aaQJNqwlR/7c+epE1ctq6xPxvfZQyOYDTWhop/JM1+KBNnnRJOFxrk3hg+GhemwztL2JyCCFELtdwDD5zRnCYGl0XnZ3i0SNBcS/ee8/+Evmj26YpSiXhHFNE0wT98XgqJUxTmKYYHxc//SRu3hT4+1eM7i0gHK6Poz5fTYiaFEavtv4DpPURV9drLwIU0zdFaw5fPNX1+iV07frYqDaju/zVUsNYe5O4+6jqGwvk3kSoy5oQtUCgFgzWtSWrWRHuhtbO+q/rromVhNvom7q2cq/Vavn8xoYQwDci3VIu162RgQFx5Ej95IMHNinZjHEX4WxdPn19gj4qnU6LcrmJ4nm9guLOkiEE4IjcEi8ClIq+PvEi4JGw+9684K/Iu5cd5+P1rvUlvqNLODim9MF4ALlvihdBl4TXK3p66kPp5KRNSv7m/6VLwmVcF8qHvtp+7Jh6R5c8fbrmxwSQ++apVgVFO+OoNf/5T/0gm1UTc6yBeFz09opbtzYQPefw0UdCCNHVVe9LkYhwHwWpXK4bUZrWhBEFuQMbfv65fsCx2zn06b17auKenjXjxDTFuXMbiJ5z4HGdI4PzfTfsjRwUGx+JhyNyq1hdMZXKBp6QYnHNRcN+SVtfjdUVYxj1S4LBhp6ZRKKWz9fy+VoiUXcZUWGw0gRHZGsWUxVHO/cBB4ejYaxbB9U01XfJi6mKo53uaO1LjVZVHboTwKpqE2Sz9cXUzk5x69ba+b/+WptTNgq63d8v+vvFp58Kv7++9jk1JUIhmxnw33+vy/zdd+vps1nhHETb5xNHj4qPPxati7UNY+aNX0x1+NdoedV2GUiIdfaGYvBY/ymjfqNlJoDRvTXMzqouF4bcNfG4KJeFc2Qlr1foet15UizWNzDK7hQlesLTp/WfZmcbvjpA80DujpRK9cVUXRczM+qvu3fXXeaZjBgZ2SCrzk71DC8kTUzYaHrfPmGaIp3eeLsYgCOyNSwt1Q9OnLD5lf2SGy4JVasilaof792rXvXvf9tcwi5FLgOA3LeXF9Gu62tAChxyWl4SmpwUqdQ6L3u5LEZH6/PdUKi+QZeXrjTNfpbJoai5DABT1W2ENyo6bDPkuWYyuc4fT1PYQGDdZFR2RCaTDZ3rimtf9vdjqoodkdsFb1R0WKr0++sH//2vEEKsrq5tEYvHRSSytkEyEBCZzNqMltLLFpGCx7O2Z8F26yXAVLWV7NwpYjEhhOjra5jm2LF6mo4OIYTo6RErKyKbFSsrazb3wIAYGFCnm//6V/1Ctohs+xL5cHburJ85c0YMDAghxJ49eD6bAJH3AKaqAEDuAEDuAEDuAEDuAEDuAEDuAEDuAEDuAEDuAEDuAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHAHIHkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDsAkDuA3AGA3AGA3AGA3AGA3AGA3AGA3AGA3AGA3AGA3AGA3AHkDgDkDgDkDgDkDgDkDgDkDgDkDgDkDgDkDgDkDgDkDgDkDiB3ACB3ACB3ACB3ACB3ACB3ACB3ACB3ACB3ACB3ACB3ALkDALkDALkDALkD8Gry/wMArsW9V7HbphQAAAAASUVORK5CYII="

class ApWindow:

    def __init__(self,list,filename,windowName,N = 0,additionalfile = None,help_word = ''):
        self.otherOut = []
        self.namelist = list #approachs name
        self.N_approach = N 
        self.windowName = windowName
        self.help = help_word
        self.score = dict()
        # creat localsave to save time while need 
        savefoder = os.path.basename(filename)
        savefoder = savefoder[:savefoder.find(".")]
        self.savefoder = savefoder #str to crate picture and save some result

        self.data = pd.read_csv(filename) 
        for column in self.data.select_dtypes(exclude=['number']).columns:
            try:
                self.data[column] = pd.to_datetime(self.data[column])
            except:
                pass

        if additionalfile != None:
            self.adddata = pd.read_csv(additionalfile)
            for column in self.adddata.select_dtypes(exclude=['number']).columns:
                try:
                    self.adddata[column] = pd.to_datetime(self.adddata[column])
                except:
                    pass

    def addData(self):
        window = sg.Window("Choose another dataset",[[sg.Input(enable_events = True, key = "-IN-",expand_x = True),sg.FileBrowse("Select Additional Dataset(if you need)",key = "-DATASET-",file_types = (("ALL Files","*.csv"),))],[sg.Button("I don't need it",key = "-DNEED-"),sg.Button("Exit")]])
        while True:
            event,value = window.read()
            if event == "-DATASET-":
                print(value["-DATASET-"])
            if event == "Exit":
                try:
                    self.adddata = pd.read_csv(value["-IN-"])
                except:
                    return None
                print(value["-IN-"])
                print(self.adddata)
                window.close()
                break
            if event == "-DNEED-":
                window.close()
                return None
        window.close()
        return 0

    def saveScore(self,savepath):
        fp = open(savepath + "score.txt",mode = "w")
        fp.write(str(self.score))
        fp.close()
        return 0

    def make_fig(self,new = True):
    #save dir
        if len(self.savefoder) == 0 :
            savepath = os.path.dirname(sys.argv[0]) + "test/image/"
        else:
            savefoder_name = os.path.basename(self.savefoder)
            savefoder_name = savefoder_name[:savefoder_name.find(".")]
            savepath = os.path.dirname(sys.argv[0]) +"/" + self.savefoder +"/" + self.windowName
    #read old file img
        if new == False:
            if os.path.exists(savepath + self.windowName + ".png"):
                return savepath + self.windowName + ".png"
            else:
                return None

    #check if there have score
        if len(self.score) == 0:
            return None

        self.saveScore(savepath)

        x = self.score.keys()
        y = self.score.values()

    #plot data and type
        plt.figure()
        plt.bar(x,y)
        plt.ylim(0,max(105,max(y)))
        plt.xticks(rotation=20)
        for a,b in zip(x,y):
            plt.text(a,b + 1,b,ha = "center")

    #save as png
        try:
            plt.savefig(savepath + self.windowName + ".png")
        except Exception:
            os.makedirs(savepath)
            plt.savefig(savepath + self.windowName + ".png")
        return savepath + self.windowName + ".png"

    def adjust(self,values):
        values = list(self.score.values())
        if len(values) == 0:
            return 0
        mean = round(sum(values) / len(values),2)
        self.score['Mean'] = mean
        return 0

    def showWindow(self):
        cb = []#check boxes
        cb.append(sg.Text("Choose approach you wish to use.(Weight in the number)"))
        for i in range(self.N_approach):
            cb.append(sg.Checkbox(text = self.namelist[i],key = i))
            cb.append(sg.Spin([i for i in range(0,100)],initial_value = 100,key = self.namelist[i].replace(".py","")))
            cb.append(sg.Text("%"))
        layout = [cb,[sg.Button("Run"),sg.Button("Exit"),sg.Button("Help")],[sg.Multiline("",key = '-OUT-',expand_x=True,expand_y=True,justification='left'),sg.Image(filename = self.make_fig(new = False),data = defaultImg,key = "-OUTPUT-")]]
        window = sg.Window(self.windowName,layout)

        while True:
            event,values = window.read()
            if event in (None,"Exit"):
                break
            if event == "Run":
                text = [x.Text for x in cb if x.get()==True]
                out = '''{}
                select mode :{}
                '''.format(self.data,text)
                window["-OUT-"].update(out)#should be output part/ should be better
                self.approaches(select_approaches = text)
                self.adjust(values)
                window["-OUTPUT-"].update(filename = self.make_fig(self.savefoder))
                #formatting output
                output_str = "Score:\n"
                for key, value in self.score.items():
                    output_str += f"{key}: {value}\n"
                output_str += '\n'
                for i in self.otherOut:
                    output_str += i + '\n'

                window["-OUT-"].update(output_str)
            if event == "Help":
                sg.popup(self.help)
        window.close()

class clickWindow:
    list = []
    windowName = ""
    otherText = ""

    def __init__(self, list,windowName,otherText = ""):
        self.list = list# for checkbox
        self.windowName = windowName
        self.otherText = otherText
        return None

    def showWindow(self):
        cb = []
        text = None
        for i in self.list:
            cb.append(sg.Checkbox(text = i,key = i))
        if self.otherText == "":
            window = sg.Window(self.windowName,[cb,[sg.Button("ok")]])
        else:
            window = sg.Window(self.windowName,[[sg.Multiline(self.otherText,size = (120, 10), disabled = True)],cb,[sg.Button("ok")]])
        while True:
            event,values = window.read()
            if event == "ok":
                text = [x.Text for x in cb if x.get()==True]
                break
            if event == None:
                break
        window.close()
        return text

class RadioGroupsWindow:
    def __init__(self,windowName, lista, listb,data,adddata ):
        self.lista = lista
        self.listb = listb
        self.selectedOptionGroupA = None
        self.selectedOptionGroupB = None
        self.windowName = windowName
        self.data = data
        self.adddata = adddata
        self.score = {}

    def countCommonElements(self,df1, df2):
        commonElements = df1.isin(df2).values.sum()
        return commonElements


    def showWindow(self):
        layout = [
            [sg.Text('Select the column whose values you want to check for equality')],
            [sg.Frame('data', [[sg.Radio(item, 'groupA', key=f'groupA_{item}')] for item in self.lista])],
            [sg.Frame('addData', [[sg.Radio(item, 'groupB', key=f'groupB_{item}')] for item in self.listb])],
            [sg.Button('Run'),sg.Button('Exit')]
        ]
        self.window = sg.Window(self.windowName, layout)
        while True:
            event, values = self.window.read()
            if event == sg.WINDOW_CLOSED:
                break
            elif event == 'Exit':
                break
            elif event == 'Run':
                self.selectedOptionGroupA = None
                for item in self.lista:
                    if values[f'groupA_{item}']:
                        self.selectedOptionGroupA = item
                        break

                self.selectedOptionGroupB = None
                for item in self.listb:
                    if values[f'groupB_{item}']:
                        self.selectedOptionGroupB = item
                        break

                NCE = self.countCommonElements(self.data[self.selectedOptionGroupA],self.data[self.selectedOptionGroupB])#number of common elements
                newDict = {str(self.selectedOptionGroupA)+"-"+str(self.selectedOptionGroupB): NCE / len(self.data[self.selectedOptionGroupA]) * 100}
                self.score.update(newDict)
                sg.popup("There are " + str(NCE) + " elements are same in " + str(len(self.data[self.selectedOptionGroupA])))
        self.window.close()
        return self.score

class readWindow:
    def __init__(self, windowName, text):
        self.windowName = windowName
        self.text = text

    def showWindow(self):
        layout = [[sg.Text(self.text)],
                  [sg.Button('OK')]]

        window = sg.Window(self.windowName, layout)

        while True:
            event, values = window.read()
            if event == sg.WINDOW_CLOSED or event == 'OK':
                break

        window.close()

class QuestionWindow:
    def __init__(self,question):
        layout = [
            [sg.Text(question,font = (None,14))],
            [sg.Button('Yes'), sg.Button('No'),sg.Button('Uncertain')]
        ]

        self.window = sg.Window('Chosoe', layout)

    def changeQuestion(self,question):
        layout = [
            [sg.Text(question,font = (None,14))],
            [sg.Button('Yes'), sg.Button('No'),sg.Button('Uncertain')]
        ]

        self.window = sg.Window('Chosoe', layout)

    def showWindow(self):
        while True:
            event, values = self.window.read()
            if event in (sg.WINDOW_CLOSED, 'Yes', 'No','Uncertain'):
                break

        self.window.close()

        if event == 'Yes':
            return 1
        elif event == 'No':
            return 0
        elif event == "Uncertain":
            return 0.5
        else:
            return 0

class FileSelection:
    def __init__(self,text = 'Choose file you need'):
        layout = [
            [sg.Text(text)],
            [sg.Input(key='-FILE-', enable_events=True), sg.FileBrowse()],
            [sg.Button('Submit')]
        ]

        self.window = sg.Window('File Select', layout)

    def showWindow(self):
        while True:
            event, values = self.window.read()

            if event in (sg.WINDOW_CLOSED, 'Submit'):
                break

        self.window.close()
        try:
            return values['-FILE-']
        except:
            return None

class TextInput:
    def __init__(self,text):
        layout = [
            [sg.Text(text)],
            [sg.InputText(key='-INPUT-')],
            [sg.Button('Submit'), sg.Button('Exit')]
        ]

        self.window = sg.Window(text, layout)

    def showWindow(self):
        while True:
            event, values = self.window.read()

            if event == sg.WINDOW_CLOSED or event == 'Exit':
                break
            elif event == 'Submit':
                input_text = values['-INPUT-']
                sg.popup(input_text)
                break

        self.window.close()
        return input_text


